# Generated by Django 6.0.4 on 2026-04-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_word_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=10),
        ),
    ]
