# Generated by Django 6.0.4 on 2026-04-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_word_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.category'),
        ),
    ]
